version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    container_name: redismemo
    hostname: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
  redis-commander:
    container_name: redis-commandermemo
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
volumes:
  db:
    driver: local
  cache:
    driver: local
  redis-commander:
    driver: local

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   env_file:
  #     - .env
  #   environment:
  #     PMA_HOST: mysql
  #   ports:
  #     - '${PHPMYADMIN_PORT}:80'
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql


