# version: '3.8'
# services:
#   db:
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - '5432:5432'
#     volumes: 
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   env_file:
  #     - .env
  #   environment:
  #     PMA_HOST: mysql
  #   ports:
  #     - '${PHPMYADMIN_PORT}:80'
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql
