export const USER_MESSAGE = {
  EMAIL_ALREADY_EXIST: 'EMAIL_ALREADY_EXIST',
  PHONE_ALREADY_EXIST: 'PHONE_ALREADY_EXIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  SEND_VERIFICATION_EMAIL_FAILED: 'SEND_VERIFICATION_EMAIL_FAILED',
};

export const MAIL_MESSAGE = {
  SEND_MAIL_FAILED: 'SEND_MAIL_FAILED',
  SEND_MAIL_SUCCESS: 'SEND_MAIL_SUCCESS',
  VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
  VERIFIED_EMAIL_SUCCESSFULLY: 'VERIFIED_EMAIL_SUCCESSFULLY',
};

export const DESCRIPTION_MESSAGE = {
  GET: {
    NOT_FOUND: 'DESCRIPTION_NOT_FOUND',
  },
};

export const CITY_MESSAGE = {
  GET: {
    NOT_FOUND: 'CITY_NOT_FOUND',
  },
};

export const AMENITIES_MESSAGE = {
  GET: {
    NOT_FOUND: 'AMENITIES_NOT_FOUND',
  },
};
