export const DESCRIPTION = [
  'House',
  'Apartment',
  'Villa',
  'Condo',
  'Townhouse',
  'Cabin',
  'Bungalow',
  'Loft',
  'Studio',
  'Treehouse',
  'Boat',
  'Castle',
  'Dorm',
  'Earth House',
  'Farm Stay',
  'Hut',
  'Igloo',
  'Lighthouse',
  'Pension',
  'Plane',
  'Ryokan',
  'Tent',
  'Tipi',
  'Train',
  'Treehouse',
  'Yurt',
];

export const AMENITIES = [
  'Wifi',
  'TV',
  'Cable TV',
  'Air conditioning',
  'Heating',
  'Kitchen',
  'Elevator',
  'Pool',
  'Hot tub',
  'Gym',
  'Indoor fireplace',
  'Buzzer/wireless intercom',
  'Breakfast',
  'Pets allowed',
  'Pets live on this property',
  'Smoking allowed',
  'Events allowed',
  'Suitable for children',
  'Wheelchair accessible',
  'Laptop friendly workspace',
  'Hair dryer',
  'Shampoo',
  'Bed linens',
  'Extra pillows and blankets',
  'Fire extinguisher',
  'First aid kit',
  'Carbon monoxide detector',
  'Smoke detector',
  'Private entrance',
];
